name: Github Action for LaTeX

inputs:
  element_files:
    required: true
  working_directory:
  compiler:
    default: latexmk
  args:
    default: "-cd -r ./.latexmkrc -f -gg"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.element_files }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.compiler }}
    - ${{ inputs.args }}
    
    
