name: Github Action for LaTeX

inputs:
  root_file:
    required: true
  # working_directory:
  compiler:
    default: latexmk
  args:
    default: "-cd -r ./.latexmkrc -f -gg"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.root_file }}
    - ${{ inputs.compiler }}
    - ${{ inputs.args }}
    
    
